services:
  php-webserver:
    build:
      context: .
      dockerfile: ./_php/Dockerfile
    container_name: CTF-PHPWebserver
    image: php:8.5-apache
    ports:
      - "81:80"
    volumes:
      # 1. Mount the entire root of the project to /workspace.
      # When VS Code attaches, it will see the root folder structure.
      - .:/workspace
      
      # 2. Re-mount the specific website folder for Apache.
      # This ensures Apache serves the correct files even though we are in a wider workspace.
      - ./:/var/www/html
    
    restart: unless-stopped
    networks:
      - public
      - private
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest 
    container_name: CTF-MySQL
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: CTFRootPassw0rd
      MYSQL_DATABASE: CyberCity
      MYSQL_USER: CyberCity
      MYSQL_PASSWORD: Cyb3rC1ty
    volumes:
      - mysql-data:/var/lib/mysql
      - ./_init_scripts:/docker-entrypoint-initdb.d
    command: --binlog-format=ROW --log-bin=mysql-bin --server-id=1
    networks:
      - private
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: CTF-PHPMyAdmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: CTFRootPassw0rd
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - public
      - private

  docs:
    image: node:current-slim
    container_name: CTF-Docs
    working_dir: /app
    ports:
      - "8001:3000"
    volumes:
      - ./_docs:/app
    command: >
      sh -c "npm install -g docsify-cli && 
             node setup.js && 
             docsify serve ."

volumes:
  mysql-data:

networks:
  public:
    driver: bridge
  private:
    internal: true