services:
  php-webserver:
    build:
      context: .
      dockerfile: ./_php/Dockerfile
    container_name: CTF-PHPWebserver
    image: php:8.5-apache
    ports:
      - "81:80"
    volumes:
      # 1. Mount the entire root of the project to /workspace.
      # When VS Code attaches, it will see the root folder structure.
      - .:/workspace
      
      # 2. Re-mount the specific website folder for Apache.
      # This ensures Apache serves the correct files even though we are in a wider workspace.
      - ./:/var/www/html
    
    restart: unless-stopped
    networks:
      - public
      - private

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: CTF-PHPMyAdmin
    environment:
      MYSQL_ROOT_PASSWORD: CTFRootPassw0rd
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - public
      - private

  docs:
    image: node:current-slim
    container_name: CTF-Docs
    working_dir: /app
    ports:
      - "8001:3000"
    volumes:
      - ./_docs:/app
    command: >
      sh -c "npm install -g docsify-cli && 
             node setup.js && 
             docsify serve ."

volumes:
  mysql-data:

networks:
  public:
    driver: bridge
  private:
    internal: true